// Referral revenue share: a referrer earns REFERRAL_SHARE_BPS (25%) of the house rake their referred
// users generate, claimable as DUSDC chips paid from the revenue wallet. All reward logic lives here so
// the routes stay thin. Everything is derived from the real Play ledger (Play.rake), never client input,
// so a user can't assert an amount and total claimable is bounded by rake that physically landed.
//
// Non-drainable by construction: the share (25% of the 1.5% fee) is strictly smaller than the fee the
// referee pays, so self-dealing loses money every round. Claims are gated by claimable = earned - claimed,
// recomputed inside a per-referrer advisory-locked txn, so concurrent/duplicate claims can't double-spend.

import type { Prisma, ReferralClaim, User } from '../../prisma/generated/client.js';
import { prismaQuery } from '../lib/prisma.ts';
import { REFERRAL_SHARE_BPS, REFERRAL_MIN_CLAIM_USD } from '../config/main-config.ts';
import { formatDusdcRaw, toDusdcRaw } from '../lib/sui/config.ts';
import { REVENUE_ENABLED } from '../lib/sui/signer.ts';
import { payDusdcFromRevenue } from '../lib/sui/dusdc.ts';
import { invalidateBal } from './plays.ts';
import type { ReferralClaimDTO } from '../types/api.ts';

// Either the top-level client or a transaction handle; both carry the model delegates we read.
type Db = typeof prismaQuery | Prisma.TransactionClient;

// The $1-min claim floor in 6dp base units (dust guard; balances keep accruing below it).
const MIN_CLAIM_RAW = toDusdcRaw(REFERRAL_MIN_CLAIM_USD);

// The referrer's share of a rake sum: floor(sum * bps / 10_000). Integer math, no float drift.
const shareOf = (rakeSum: bigint): bigint => (rakeSum * REFERRAL_SHARE_BPS) / 10_000n;

// Total rake generated by this referrer's referees. Only minted plays carry rake > 0, so pending/error
// plays never accrue (no false earnings).
async function sumRake(db: Db, referrerId: string): Promise<bigint> {
  const agg = await db.play.aggregate({
    where: { user: { referredById: referrerId }, rake: { gt: 0n } },
    _sum: { rake: true },
  });
  return agg._sum.rake ?? 0n;
}

// Already reserved or paid out (pending + paid); a failed claim releases its reservation, so it's excluded.
async function sumClaimed(db: Db, referrerId: string): Promise<bigint> {
  const agg = await db.referralClaim.aggregate({
    where: { referrerId, status: { in: ['pending', 'paid'] } },
    _sum: { amount: true },
  });
  return agg._sum.amount ?? 0n;
}

// Lifetime earned = share of all referee rake. Derived, self-healing, backfillable from the ledger anytime.
export async function earnedRaw(referrerId: string): Promise<bigint> {
  return shareOf(await sumRake(prismaQuery, referrerId));
}

// Earned, already-claimed, and the spendable remainder in one shot (the /referral screen needs all three).
export async function referralRewards(referrerId: string): Promise<{ earned: bigint; claimed: bigint; claimable: bigint }> {
  const [earned, claimed] = await Promise.all([earnedRaw(referrerId), sumClaimed(prismaQuery, referrerId)]);
  const claimable = earned - claimed;
  return { earned, claimed, claimable: claimable > 0n ? claimable : 0n };
}

// Per-referee earned, keyed by referee userId (display only; per-row rounding vs the aggregate is sub-cent).
export async function perRefereeEarned(referrerId: string): Promise<Map<string, bigint>> {
  const groups = await prismaQuery.play.groupBy({
    by: ['userId'],
    where: { user: { referredById: referrerId }, rake: { gt: 0n } },
    _sum: { rake: true },
  });
  const map = new Map<string, bigint>();
  for (const g of groups) map.set(g.userId, shareOf(g._sum.rake ?? 0n));
  return map;
}

// Recent claim rows, newest first, bounded.
export async function listClaims(referrerId: string, take = 50): Promise<ReferralClaim[]> {
  return prismaQuery.referralClaim.findMany({ where: { referrerId }, orderBy: { createdAt: 'desc' }, take });
}

export const MIN_CLAIM_USD = REFERRAL_MIN_CLAIM_USD;
export const SHARE_PCT = Number(REFERRAL_SHARE_BPS) / 100;

export type ReferralErrorCode = 'REFERRAL_REWARDS_DISABLED' | 'REFERRAL_BELOW_MIN' | 'REFERRAL_CLAIM_FAILED';

export class ReferralError extends Error {
  code: ReferralErrorCode;
  constructor(code: ReferralErrorCode, message: string) {
    super(message);
    this.name = 'ReferralError';
    this.code = code;
  }
}

export const httpStatusForReferralError = (code: ReferralErrorCode): number =>
  code === 'REFERRAL_CLAIM_FAILED' ? 500 : code === 'REFERRAL_REWARDS_DISABLED' ? 409 : 400;

// Claim the spendable balance into the referrer's own DUSDC chips. Two phases: RESERVE a pending claim
// inside a per-referrer advisory-locked txn (recompute claimable there so concurrent claims can't
// double-spend), then PAY outside the txn. A crash between the two leaves a `pending` claim: funds are
// locked, never lost (safe, not a drain). submitAndConfirm makes the normal path a clean paid/failed.
export async function claimReferral(user: User): Promise<ReferralClaim> {
  if (!REVENUE_ENABLED) throw new ReferralError('REFERRAL_REWARDS_DISABLED', 'Referral rewards are not available yet.');

  const reserved = await prismaQuery.$transaction(async (tx) => {
    // Per-referrer advisory lock (auto-released at commit) so a second concurrent claim recomputes only
    // AFTER this txn's pending row commits and sees claimable = 0. Same primitive as leader-lock.ts;
    // hashtext maps the name to the bigint key the lock wants.
    await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`referral:${user.id}`}))`;
    const [earned, claimed] = await Promise.all([sumRake(tx, user.id).then(shareOf), sumClaimed(tx, user.id)]);
    const claimable = earned - claimed;
    if (claimable < MIN_CLAIM_RAW) {
      throw new ReferralError('REFERRAL_BELOW_MIN', `You need at least $${REFERRAL_MIN_CLAIM_USD.toFixed(2)} in rewards to claim.`);
    }
    // The pending row immediately reduces claimable for any concurrent claim (reservation).
    return tx.referralClaim.create({ data: { referrerId: user.id, amount: claimable, status: 'pending' } });
  });

  // Pay the reserved amount out of the revenue wallet to the referrer's own address (playable chips).
  try {
    const txDigest = await payDusdcFromRevenue(user.address, reserved.amount);
    const paid = await prismaQuery.referralClaim.update({
      where: { id: reserved.id },
      data: { status: 'paid', txDigest, paidAt: new Date() },
    });
    invalidateBal(user.id); // chips just landed; the next balance read must refresh
    return paid;
  } catch (e) {
    // Payout failed: release the reservation so the amount becomes claimable again (never lost).
    await prismaQuery.referralClaim.update({ where: { id: reserved.id }, data: { status: 'failed' } }).catch(() => {});
    console.error('[referral] claim payout failed:', e instanceof Error ? e.message : e);
    throw new ReferralError('REFERRAL_CLAIM_FAILED', 'Could not pay out your claim right now. Your rewards are safe, try again.');
  }
}

export function toReferralClaimDTO(c: ReferralClaim): ReferralClaimDTO {
  return {
    id: c.id,
    amount: formatDusdcRaw(c.amount),
    status: c.status as ReferralClaimDTO['status'],
    txDigest: c.txDigest,
    createdAt: c.createdAt.toISOString(),
  };
}
