/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsWalletRouteImport } from './routes/tools/wallet'
import { Route as AppMenuIndexRouteImport } from './routes/_app/menu/index'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games/index'
import { Route as AppMenuStatsRouteImport } from './routes/_app/menu/stats'
import { Route as AppMenuSettingsRouteImport } from './routes/_app/menu/settings'
import { Route as AppMenuCustomizeRouteImport } from './routes/_app/menu/customize'
import { Route as AppMenuAchievementsRouteImport } from './routes/_app/menu/achievements'
import { Route as AppGamesTapRouteImport } from './routes/_app/games/tap'
import { Route as AppGamesRangeRouteImport } from './routes/_app/games/range'
import { Route as AppGamesLuckyRouteImport } from './routes/_app/games/lucky'
import { Route as AppGamesLineRiderRouteImport } from './routes/_app/games/line-rider'
import { Route as AppGamesCandleHopRouteImport } from './routes/_app/games/candle-hop'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWalletRoute = ToolsWalletRouteImport.update({
  id: '/tools/wallet',
  path: '/tools/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuStatsRoute = AppMenuStatsRouteImport.update({
  id: '/menu/stats',
  path: '/menu/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuSettingsRoute = AppMenuSettingsRouteImport.update({
  id: '/menu/settings',
  path: '/menu/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuCustomizeRoute = AppMenuCustomizeRouteImport.update({
  id: '/menu/customize',
  path: '/menu/customize',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuAchievementsRoute = AppMenuAchievementsRouteImport.update({
  id: '/menu/achievements',
  path: '/menu/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesTapRoute = AppGamesTapRouteImport.update({
  id: '/games/tap',
  path: '/games/tap',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRangeRoute = AppGamesRangeRouteImport.update({
  id: '/games/range',
  path: '/games/range',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLuckyRoute = AppGamesLuckyRouteImport.update({
  id: '/games/lucky',
  path: '/games/lucky',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLineRiderRoute = AppGamesLineRiderRouteImport.update({
  id: '/games/line-rider',
  path: '/games/line-rider',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesCandleHopRoute = AppGamesCandleHopRouteImport.update({
  id: '/games/candle-hop',
  path: '/games/candle-hop',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/design-system': typeof DesignSystemRoute
  '/tools/wallet': typeof ToolsWalletRoute
  '/games/candle-hop': typeof AppGamesCandleHopRoute
  '/games/line-rider': typeof AppGamesLineRiderRoute
  '/games/lucky': typeof AppGamesLuckyRoute
  '/games/range': typeof AppGamesRangeRoute
  '/games/tap': typeof AppGamesTapRoute
  '/menu/achievements': typeof AppMenuAchievementsRoute
  '/menu/customize': typeof AppMenuCustomizeRoute
  '/menu/settings': typeof AppMenuSettingsRoute
  '/menu/stats': typeof AppMenuStatsRoute
  '/games/': typeof AppGamesIndexRoute
  '/menu/': typeof AppMenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/design-system': typeof DesignSystemRoute
  '/tools/wallet': typeof ToolsWalletRoute
  '/games/candle-hop': typeof AppGamesCandleHopRoute
  '/games/line-rider': typeof AppGamesLineRiderRoute
  '/games/lucky': typeof AppGamesLuckyRoute
  '/games/range': typeof AppGamesRangeRoute
  '/games/tap': typeof AppGamesTapRoute
  '/menu/achievements': typeof AppMenuAchievementsRoute
  '/menu/customize': typeof AppMenuCustomizeRoute
  '/menu/settings': typeof AppMenuSettingsRoute
  '/menu/stats': typeof AppMenuStatsRoute
  '/games': typeof AppGamesIndexRoute
  '/menu': typeof AppMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRoute
  '/design-system': typeof DesignSystemRoute
  '/tools/wallet': typeof ToolsWalletRoute
  '/_app/games/candle-hop': typeof AppGamesCandleHopRoute
  '/_app/games/line-rider': typeof AppGamesLineRiderRoute
  '/_app/games/lucky': typeof AppGamesLuckyRoute
  '/_app/games/range': typeof AppGamesRangeRoute
  '/_app/games/tap': typeof AppGamesTapRoute
  '/_app/menu/achievements': typeof AppMenuAchievementsRoute
  '/_app/menu/customize': typeof AppMenuCustomizeRoute
  '/_app/menu/settings': typeof AppMenuSettingsRoute
  '/_app/menu/stats': typeof AppMenuStatsRoute
  '/_app/games/': typeof AppGamesIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/design-system'
    | '/tools/wallet'
    | '/games/candle-hop'
    | '/games/line-rider'
    | '/games/lucky'
    | '/games/range'
    | '/games/tap'
    | '/menu/achievements'
    | '/menu/customize'
    | '/menu/settings'
    | '/menu/stats'
    | '/games/'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/design-system'
    | '/tools/wallet'
    | '/games/candle-hop'
    | '/games/line-rider'
    | '/games/lucky'
    | '/games/range'
    | '/games/tap'
    | '/menu/achievements'
    | '/menu/customize'
    | '/menu/settings'
    | '/menu/stats'
    | '/games'
    | '/menu'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/console'
    | '/design-system'
    | '/tools/wallet'
    | '/_app/games/candle-hop'
    | '/_app/games/line-rider'
    | '/_app/games/lucky'
    | '/_app/games/range'
    | '/_app/games/tap'
    | '/_app/menu/achievements'
    | '/_app/menu/customize'
    | '/_app/menu/settings'
    | '/_app/menu/stats'
    | '/_app/games/'
    | '/_app/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ToolsWalletRoute: typeof ToolsWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/wallet': {
      id: '/tools/wallet'
      path: '/tools/wallet'
      fullPath: '/tools/wallet'
      preLoaderRoute: typeof ToolsWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/stats': {
      id: '/_app/menu/stats'
      path: '/menu/stats'
      fullPath: '/menu/stats'
      preLoaderRoute: typeof AppMenuStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/settings': {
      id: '/_app/menu/settings'
      path: '/menu/settings'
      fullPath: '/menu/settings'
      preLoaderRoute: typeof AppMenuSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/customize': {
      id: '/_app/menu/customize'
      path: '/menu/customize'
      fullPath: '/menu/customize'
      preLoaderRoute: typeof AppMenuCustomizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/achievements': {
      id: '/_app/menu/achievements'
      path: '/menu/achievements'
      fullPath: '/menu/achievements'
      preLoaderRoute: typeof AppMenuAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/tap': {
      id: '/_app/games/tap'
      path: '/games/tap'
      fullPath: '/games/tap'
      preLoaderRoute: typeof AppGamesTapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/range': {
      id: '/_app/games/range'
      path: '/games/range'
      fullPath: '/games/range'
      preLoaderRoute: typeof AppGamesRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/lucky': {
      id: '/_app/games/lucky'
      path: '/games/lucky'
      fullPath: '/games/lucky'
      preLoaderRoute: typeof AppGamesLuckyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/line-rider': {
      id: '/_app/games/line-rider'
      path: '/games/line-rider'
      fullPath: '/games/line-rider'
      preLoaderRoute: typeof AppGamesLineRiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/candle-hop': {
      id: '/_app/games/candle-hop'
      path: '/games/candle-hop'
      fullPath: '/games/candle-hop'
      preLoaderRoute: typeof AppGamesCandleHopRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGamesCandleHopRoute: typeof AppGamesCandleHopRoute
  AppGamesLineRiderRoute: typeof AppGamesLineRiderRoute
  AppGamesLuckyRoute: typeof AppGamesLuckyRoute
  AppGamesRangeRoute: typeof AppGamesRangeRoute
  AppGamesTapRoute: typeof AppGamesTapRoute
  AppMenuAchievementsRoute: typeof AppMenuAchievementsRoute
  AppMenuCustomizeRoute: typeof AppMenuCustomizeRoute
  AppMenuSettingsRoute: typeof AppMenuSettingsRoute
  AppMenuStatsRoute: typeof AppMenuStatsRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGamesCandleHopRoute: AppGamesCandleHopRoute,
  AppGamesLineRiderRoute: AppGamesLineRiderRoute,
  AppGamesLuckyRoute: AppGamesLuckyRoute,
  AppGamesRangeRoute: AppGamesRangeRoute,
  AppGamesTapRoute: AppGamesTapRoute,
  AppMenuAchievementsRoute: AppMenuAchievementsRoute,
  AppMenuCustomizeRoute: AppMenuCustomizeRoute,
  AppMenuSettingsRoute: AppMenuSettingsRoute,
  AppMenuStatsRoute: AppMenuStatsRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  DesignSystemRoute: DesignSystemRoute,
  ToolsWalletRoute: ToolsWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
