/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoundsRouteImport } from './routes/sounds'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ConsoleTransparentRouteImport } from './routes/console-transparent'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AtChar123handleChar125RouteImport } from './routes/@{$handle}'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AppMenuIndexRouteImport } from './routes/_app/menu/index'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games/index'
import { Route as AppMenuWithdrawRouteImport } from './routes/_app/menu/withdraw'
import { Route as AppMenuUsernameRouteImport } from './routes/_app/menu/username'
import { Route as AppMenuShareRouteImport } from './routes/_app/menu/share'
import { Route as AppMenuSettingsRouteImport } from './routes/_app/menu/settings'
import { Route as AppMenuReferralsRouteImport } from './routes/_app/menu/referrals'
import { Route as AppMenuLeaderboardRouteImport } from './routes/_app/menu/leaderboard'
import { Route as AppMenuHistoryRouteImport } from './routes/_app/menu/history'
import { Route as AppMenuDepositRouteImport } from './routes/_app/menu/deposit'
import { Route as AppMenuCustomizeRouteImport } from './routes/_app/menu/customize'
import { Route as AppMenuAchievementsRouteImport } from './routes/_app/menu/achievements'
import { Route as AppMenuAccountRouteImport } from './routes/_app/menu/account'
import { Route as AppMenuAboutRouteImport } from './routes/_app/menu/about'
import { Route as AppGamesRangeV2RouteImport } from './routes/_app/games/range-v2'
import { Route as AppGamesRangeRouteImport } from './routes/_app/games/range'
import { Route as AppGamesMoonshotRouteImport } from './routes/_app/games/moonshot'
import { Route as AppGamesLuckyRouteImport } from './routes/_app/games/lucky'
import { Route as AppGamesLineRiderRouteImport } from './routes/_app/games/line-rider'
import { Route as AppGamesFlappyPiperRouteImport } from './routes/_app/games/flappy-piper'

const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTransparentRoute = ConsoleTransparentRouteImport.update({
  id: '/console-transparent',
  path: '/console-transparent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125Route = AtChar123handleChar125RouteImport.update({
  id: '/@{$handle}',
  path: '/@{$handle}',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuWithdrawRoute = AppMenuWithdrawRouteImport.update({
  id: '/menu/withdraw',
  path: '/menu/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuUsernameRoute = AppMenuUsernameRouteImport.update({
  id: '/menu/username',
  path: '/menu/username',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuShareRoute = AppMenuShareRouteImport.update({
  id: '/menu/share',
  path: '/menu/share',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuSettingsRoute = AppMenuSettingsRouteImport.update({
  id: '/menu/settings',
  path: '/menu/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuReferralsRoute = AppMenuReferralsRouteImport.update({
  id: '/menu/referrals',
  path: '/menu/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuLeaderboardRoute = AppMenuLeaderboardRouteImport.update({
  id: '/menu/leaderboard',
  path: '/menu/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuHistoryRoute = AppMenuHistoryRouteImport.update({
  id: '/menu/history',
  path: '/menu/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuDepositRoute = AppMenuDepositRouteImport.update({
  id: '/menu/deposit',
  path: '/menu/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuCustomizeRoute = AppMenuCustomizeRouteImport.update({
  id: '/menu/customize',
  path: '/menu/customize',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuAchievementsRoute = AppMenuAchievementsRouteImport.update({
  id: '/menu/achievements',
  path: '/menu/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuAccountRoute = AppMenuAccountRouteImport.update({
  id: '/menu/account',
  path: '/menu/account',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuAboutRoute = AppMenuAboutRouteImport.update({
  id: '/menu/about',
  path: '/menu/about',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRangeV2Route = AppGamesRangeV2RouteImport.update({
  id: '/games/range-v2',
  path: '/games/range-v2',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRangeRoute = AppGamesRangeRouteImport.update({
  id: '/games/range',
  path: '/games/range',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesMoonshotRoute = AppGamesMoonshotRouteImport.update({
  id: '/games/moonshot',
  path: '/games/moonshot',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLuckyRoute = AppGamesLuckyRouteImport.update({
  id: '/games/lucky',
  path: '/games/lucky',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLineRiderRoute = AppGamesLineRiderRouteImport.update({
  id: '/games/line-rider',
  path: '/games/line-rider',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesFlappyPiperRoute = AppGamesFlappyPiperRouteImport.update({
  id: '/games/flappy-piper',
  path: '/games/flappy-piper',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/': typeof AppIndexRoute
  '/console': typeof ConsoleRoute
  '/console-transparent': typeof ConsoleTransparentRoute
  '/design-system': typeof DesignSystemRoute
  '/export': typeof ExportRoute
  '/pitch': typeof PitchRoute
  '/sounds': typeof SoundsRoute
  '/r/$code': typeof RCodeRoute
  '/games/flappy-piper': typeof AppGamesFlappyPiperRoute
  '/games/line-rider': typeof AppGamesLineRiderRoute
  '/games/lucky': typeof AppGamesLuckyRoute
  '/games/moonshot': typeof AppGamesMoonshotRoute
  '/games/range': typeof AppGamesRangeRoute
  '/games/range-v2': typeof AppGamesRangeV2Route
  '/menu/about': typeof AppMenuAboutRoute
  '/menu/account': typeof AppMenuAccountRoute
  '/menu/achievements': typeof AppMenuAchievementsRoute
  '/menu/customize': typeof AppMenuCustomizeRoute
  '/menu/deposit': typeof AppMenuDepositRoute
  '/menu/history': typeof AppMenuHistoryRoute
  '/menu/leaderboard': typeof AppMenuLeaderboardRoute
  '/menu/referrals': typeof AppMenuReferralsRoute
  '/menu/settings': typeof AppMenuSettingsRoute
  '/menu/share': typeof AppMenuShareRoute
  '/menu/username': typeof AppMenuUsernameRoute
  '/menu/withdraw': typeof AppMenuWithdrawRoute
  '/games/': typeof AppGamesIndexRoute
  '/menu/': typeof AppMenuIndexRoute
}
export interface FileRoutesByTo {
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/console': typeof ConsoleRoute
  '/console-transparent': typeof ConsoleTransparentRoute
  '/design-system': typeof DesignSystemRoute
  '/export': typeof ExportRoute
  '/pitch': typeof PitchRoute
  '/sounds': typeof SoundsRoute
  '/r/$code': typeof RCodeRoute
  '/': typeof AppIndexRoute
  '/games/flappy-piper': typeof AppGamesFlappyPiperRoute
  '/games/line-rider': typeof AppGamesLineRiderRoute
  '/games/lucky': typeof AppGamesLuckyRoute
  '/games/moonshot': typeof AppGamesMoonshotRoute
  '/games/range': typeof AppGamesRangeRoute
  '/games/range-v2': typeof AppGamesRangeV2Route
  '/menu/about': typeof AppMenuAboutRoute
  '/menu/account': typeof AppMenuAccountRoute
  '/menu/achievements': typeof AppMenuAchievementsRoute
  '/menu/customize': typeof AppMenuCustomizeRoute
  '/menu/deposit': typeof AppMenuDepositRoute
  '/menu/history': typeof AppMenuHistoryRoute
  '/menu/leaderboard': typeof AppMenuLeaderboardRoute
  '/menu/referrals': typeof AppMenuReferralsRoute
  '/menu/settings': typeof AppMenuSettingsRoute
  '/menu/share': typeof AppMenuShareRoute
  '/menu/username': typeof AppMenuUsernameRoute
  '/menu/withdraw': typeof AppMenuWithdrawRoute
  '/games': typeof AppGamesIndexRoute
  '/menu': typeof AppMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/_app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRoute
  '/console-transparent': typeof ConsoleTransparentRoute
  '/design-system': typeof DesignSystemRoute
  '/export': typeof ExportRoute
  '/pitch': typeof PitchRoute
  '/sounds': typeof SoundsRoute
  '/r/$code': typeof RCodeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/games/flappy-piper': typeof AppGamesFlappyPiperRoute
  '/_app/games/line-rider': typeof AppGamesLineRiderRoute
  '/_app/games/lucky': typeof AppGamesLuckyRoute
  '/_app/games/moonshot': typeof AppGamesMoonshotRoute
  '/_app/games/range': typeof AppGamesRangeRoute
  '/_app/games/range-v2': typeof AppGamesRangeV2Route
  '/_app/menu/about': typeof AppMenuAboutRoute
  '/_app/menu/account': typeof AppMenuAccountRoute
  '/_app/menu/achievements': typeof AppMenuAchievementsRoute
  '/_app/menu/customize': typeof AppMenuCustomizeRoute
  '/_app/menu/deposit': typeof AppMenuDepositRoute
  '/_app/menu/history': typeof AppMenuHistoryRoute
  '/_app/menu/leaderboard': typeof AppMenuLeaderboardRoute
  '/_app/menu/referrals': typeof AppMenuReferralsRoute
  '/_app/menu/settings': typeof AppMenuSettingsRoute
  '/_app/menu/share': typeof AppMenuShareRoute
  '/_app/menu/username': typeof AppMenuUsernameRoute
  '/_app/menu/withdraw': typeof AppMenuWithdrawRoute
  '/_app/games/': typeof AppGamesIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/@{$handle}'
    | '/'
    | '/console'
    | '/console-transparent'
    | '/design-system'
    | '/export'
    | '/pitch'
    | '/sounds'
    | '/r/$code'
    | '/games/flappy-piper'
    | '/games/line-rider'
    | '/games/lucky'
    | '/games/moonshot'
    | '/games/range'
    | '/games/range-v2'
    | '/menu/about'
    | '/menu/account'
    | '/menu/achievements'
    | '/menu/customize'
    | '/menu/deposit'
    | '/menu/history'
    | '/menu/leaderboard'
    | '/menu/referrals'
    | '/menu/settings'
    | '/menu/share'
    | '/menu/username'
    | '/menu/withdraw'
    | '/games/'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/@{$handle}'
    | '/console'
    | '/console-transparent'
    | '/design-system'
    | '/export'
    | '/pitch'
    | '/sounds'
    | '/r/$code'
    | '/'
    | '/games/flappy-piper'
    | '/games/line-rider'
    | '/games/lucky'
    | '/games/moonshot'
    | '/games/range'
    | '/games/range-v2'
    | '/menu/about'
    | '/menu/account'
    | '/menu/achievements'
    | '/menu/customize'
    | '/menu/deposit'
    | '/menu/history'
    | '/menu/leaderboard'
    | '/menu/referrals'
    | '/menu/settings'
    | '/menu/share'
    | '/menu/username'
    | '/menu/withdraw'
    | '/games'
    | '/menu'
  id:
    | '__root__'
    | '/@{$handle}'
    | '/_app'
    | '/console'
    | '/console-transparent'
    | '/design-system'
    | '/export'
    | '/pitch'
    | '/sounds'
    | '/r/$code'
    | '/_app/'
    | '/_app/games/flappy-piper'
    | '/_app/games/line-rider'
    | '/_app/games/lucky'
    | '/_app/games/moonshot'
    | '/_app/games/range'
    | '/_app/games/range-v2'
    | '/_app/menu/about'
    | '/_app/menu/account'
    | '/_app/menu/achievements'
    | '/_app/menu/customize'
    | '/_app/menu/deposit'
    | '/_app/menu/history'
    | '/_app/menu/leaderboard'
    | '/_app/menu/referrals'
    | '/_app/menu/settings'
    | '/_app/menu/share'
    | '/_app/menu/username'
    | '/_app/menu/withdraw'
    | '/_app/games/'
    | '/_app/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AtChar123handleChar125Route: typeof AtChar123handleChar125Route
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  ConsoleTransparentRoute: typeof ConsoleTransparentRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ExportRoute: typeof ExportRoute
  PitchRoute: typeof PitchRoute
  SoundsRoute: typeof SoundsRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console-transparent': {
      id: '/console-transparent'
      path: '/console-transparent'
      fullPath: '/console-transparent'
      preLoaderRoute: typeof ConsoleTransparentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}': {
      id: '/@{$handle}'
      path: '/@{$handle}'
      fullPath: '/@{$handle}'
      preLoaderRoute: typeof AtChar123handleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/withdraw': {
      id: '/_app/menu/withdraw'
      path: '/menu/withdraw'
      fullPath: '/menu/withdraw'
      preLoaderRoute: typeof AppMenuWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/username': {
      id: '/_app/menu/username'
      path: '/menu/username'
      fullPath: '/menu/username'
      preLoaderRoute: typeof AppMenuUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/share': {
      id: '/_app/menu/share'
      path: '/menu/share'
      fullPath: '/menu/share'
      preLoaderRoute: typeof AppMenuShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/settings': {
      id: '/_app/menu/settings'
      path: '/menu/settings'
      fullPath: '/menu/settings'
      preLoaderRoute: typeof AppMenuSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/referrals': {
      id: '/_app/menu/referrals'
      path: '/menu/referrals'
      fullPath: '/menu/referrals'
      preLoaderRoute: typeof AppMenuReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/leaderboard': {
      id: '/_app/menu/leaderboard'
      path: '/menu/leaderboard'
      fullPath: '/menu/leaderboard'
      preLoaderRoute: typeof AppMenuLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/history': {
      id: '/_app/menu/history'
      path: '/menu/history'
      fullPath: '/menu/history'
      preLoaderRoute: typeof AppMenuHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/deposit': {
      id: '/_app/menu/deposit'
      path: '/menu/deposit'
      fullPath: '/menu/deposit'
      preLoaderRoute: typeof AppMenuDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/customize': {
      id: '/_app/menu/customize'
      path: '/menu/customize'
      fullPath: '/menu/customize'
      preLoaderRoute: typeof AppMenuCustomizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/achievements': {
      id: '/_app/menu/achievements'
      path: '/menu/achievements'
      fullPath: '/menu/achievements'
      preLoaderRoute: typeof AppMenuAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/account': {
      id: '/_app/menu/account'
      path: '/menu/account'
      fullPath: '/menu/account'
      preLoaderRoute: typeof AppMenuAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/about': {
      id: '/_app/menu/about'
      path: '/menu/about'
      fullPath: '/menu/about'
      preLoaderRoute: typeof AppMenuAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/range-v2': {
      id: '/_app/games/range-v2'
      path: '/games/range-v2'
      fullPath: '/games/range-v2'
      preLoaderRoute: typeof AppGamesRangeV2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/range': {
      id: '/_app/games/range'
      path: '/games/range'
      fullPath: '/games/range'
      preLoaderRoute: typeof AppGamesRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/moonshot': {
      id: '/_app/games/moonshot'
      path: '/games/moonshot'
      fullPath: '/games/moonshot'
      preLoaderRoute: typeof AppGamesMoonshotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/lucky': {
      id: '/_app/games/lucky'
      path: '/games/lucky'
      fullPath: '/games/lucky'
      preLoaderRoute: typeof AppGamesLuckyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/line-rider': {
      id: '/_app/games/line-rider'
      path: '/games/line-rider'
      fullPath: '/games/line-rider'
      preLoaderRoute: typeof AppGamesLineRiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/flappy-piper': {
      id: '/_app/games/flappy-piper'
      path: '/games/flappy-piper'
      fullPath: '/games/flappy-piper'
      preLoaderRoute: typeof AppGamesFlappyPiperRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppGamesFlappyPiperRoute: typeof AppGamesFlappyPiperRoute
  AppGamesLineRiderRoute: typeof AppGamesLineRiderRoute
  AppGamesLuckyRoute: typeof AppGamesLuckyRoute
  AppGamesMoonshotRoute: typeof AppGamesMoonshotRoute
  AppGamesRangeRoute: typeof AppGamesRangeRoute
  AppGamesRangeV2Route: typeof AppGamesRangeV2Route
  AppMenuAboutRoute: typeof AppMenuAboutRoute
  AppMenuAccountRoute: typeof AppMenuAccountRoute
  AppMenuAchievementsRoute: typeof AppMenuAchievementsRoute
  AppMenuCustomizeRoute: typeof AppMenuCustomizeRoute
  AppMenuDepositRoute: typeof AppMenuDepositRoute
  AppMenuHistoryRoute: typeof AppMenuHistoryRoute
  AppMenuLeaderboardRoute: typeof AppMenuLeaderboardRoute
  AppMenuReferralsRoute: typeof AppMenuReferralsRoute
  AppMenuSettingsRoute: typeof AppMenuSettingsRoute
  AppMenuShareRoute: typeof AppMenuShareRoute
  AppMenuUsernameRoute: typeof AppMenuUsernameRoute
  AppMenuWithdrawRoute: typeof AppMenuWithdrawRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppGamesFlappyPiperRoute: AppGamesFlappyPiperRoute,
  AppGamesLineRiderRoute: AppGamesLineRiderRoute,
  AppGamesLuckyRoute: AppGamesLuckyRoute,
  AppGamesMoonshotRoute: AppGamesMoonshotRoute,
  AppGamesRangeRoute: AppGamesRangeRoute,
  AppGamesRangeV2Route: AppGamesRangeV2Route,
  AppMenuAboutRoute: AppMenuAboutRoute,
  AppMenuAccountRoute: AppMenuAccountRoute,
  AppMenuAchievementsRoute: AppMenuAchievementsRoute,
  AppMenuCustomizeRoute: AppMenuCustomizeRoute,
  AppMenuDepositRoute: AppMenuDepositRoute,
  AppMenuHistoryRoute: AppMenuHistoryRoute,
  AppMenuLeaderboardRoute: AppMenuLeaderboardRoute,
  AppMenuReferralsRoute: AppMenuReferralsRoute,
  AppMenuSettingsRoute: AppMenuSettingsRoute,
  AppMenuShareRoute: AppMenuShareRoute,
  AppMenuUsernameRoute: AppMenuUsernameRoute,
  AppMenuWithdrawRoute: AppMenuWithdrawRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AtChar123handleChar125Route: AtChar123handleChar125Route,
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  ConsoleTransparentRoute: ConsoleTransparentRoute,
  DesignSystemRoute: DesignSystemRoute,
  ExportRoute: ExportRoute,
  PitchRoute: PitchRoute,
  SoundsRoute: SoundsRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
