/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ConsoleTransparentRouteImport } from './routes/console-transparent'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ToolsWalletRouteImport } from './routes/tools/wallet'
import { Route as AppMenuIndexRouteImport } from './routes/_app/menu/index'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games/index'
import { Route as AppMenuWithdrawRouteImport } from './routes/_app/menu/withdraw'
import { Route as AppMenuUsernameRouteImport } from './routes/_app/menu/username'
import { Route as AppMenuStatsRouteImport } from './routes/_app/menu/stats'
import { Route as AppMenuSettingsRouteImport } from './routes/_app/menu/settings'
import { Route as AppMenuLeaderboardRouteImport } from './routes/_app/menu/leaderboard'
import { Route as AppMenuHistoryRouteImport } from './routes/_app/menu/history'
import { Route as AppMenuDepositRouteImport } from './routes/_app/menu/deposit'
import { Route as AppMenuCustomizeRouteImport } from './routes/_app/menu/customize'
import { Route as AppMenuAchievementsRouteImport } from './routes/_app/menu/achievements'
import { Route as AppGamesRangeRouteImport } from './routes/_app/games/range'
import { Route as AppGamesMoonshotRouteImport } from './routes/_app/games/moonshot'
import { Route as AppGamesLuckyRouteImport } from './routes/_app/games/lucky'
import { Route as AppGamesLineRiderRouteImport } from './routes/_app/games/line-rider'
import { Route as AppGamesCandleHopRouteImport } from './routes/_app/games/candle-hop'

const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleTransparentRoute = ConsoleTransparentRouteImport.update({
  id: '/console-transparent',
  path: '/console-transparent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ToolsWalletRoute = ToolsWalletRouteImport.update({
  id: '/tools/wallet',
  path: '/tools/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuWithdrawRoute = AppMenuWithdrawRouteImport.update({
  id: '/menu/withdraw',
  path: '/menu/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuUsernameRoute = AppMenuUsernameRouteImport.update({
  id: '/menu/username',
  path: '/menu/username',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuStatsRoute = AppMenuStatsRouteImport.update({
  id: '/menu/stats',
  path: '/menu/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuSettingsRoute = AppMenuSettingsRouteImport.update({
  id: '/menu/settings',
  path: '/menu/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuLeaderboardRoute = AppMenuLeaderboardRouteImport.update({
  id: '/menu/leaderboard',
  path: '/menu/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuHistoryRoute = AppMenuHistoryRouteImport.update({
  id: '/menu/history',
  path: '/menu/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuDepositRoute = AppMenuDepositRouteImport.update({
  id: '/menu/deposit',
  path: '/menu/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuCustomizeRoute = AppMenuCustomizeRouteImport.update({
  id: '/menu/customize',
  path: '/menu/customize',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuAchievementsRoute = AppMenuAchievementsRouteImport.update({
  id: '/menu/achievements',
  path: '/menu/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRangeRoute = AppGamesRangeRouteImport.update({
  id: '/games/range',
  path: '/games/range',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesMoonshotRoute = AppGamesMoonshotRouteImport.update({
  id: '/games/moonshot',
  path: '/games/moonshot',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLuckyRoute = AppGamesLuckyRouteImport.update({
  id: '/games/lucky',
  path: '/games/lucky',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLineRiderRoute = AppGamesLineRiderRouteImport.update({
  id: '/games/line-rider',
  path: '/games/line-rider',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesCandleHopRoute = AppGamesCandleHopRouteImport.update({
  id: '/games/candle-hop',
  path: '/games/candle-hop',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/console': typeof ConsoleRoute
  '/console-transparent': typeof ConsoleTransparentRoute
  '/design-system': typeof DesignSystemRoute
  '/export': typeof ExportRoute
  '/pitch': typeof PitchRoute
  '/tools/wallet': typeof ToolsWalletRoute
  '/games/candle-hop': typeof AppGamesCandleHopRoute
  '/games/line-rider': typeof AppGamesLineRiderRoute
  '/games/lucky': typeof AppGamesLuckyRoute
  '/games/moonshot': typeof AppGamesMoonshotRoute
  '/games/range': typeof AppGamesRangeRoute
  '/menu/achievements': typeof AppMenuAchievementsRoute
  '/menu/customize': typeof AppMenuCustomizeRoute
  '/menu/deposit': typeof AppMenuDepositRoute
  '/menu/history': typeof AppMenuHistoryRoute
  '/menu/leaderboard': typeof AppMenuLeaderboardRoute
  '/menu/settings': typeof AppMenuSettingsRoute
  '/menu/stats': typeof AppMenuStatsRoute
  '/menu/username': typeof AppMenuUsernameRoute
  '/menu/withdraw': typeof AppMenuWithdrawRoute
  '/games/': typeof AppGamesIndexRoute
  '/menu/': typeof AppMenuIndexRoute
}
export interface FileRoutesByTo {
  '/console': typeof ConsoleRoute
  '/console-transparent': typeof ConsoleTransparentRoute
  '/design-system': typeof DesignSystemRoute
  '/export': typeof ExportRoute
  '/pitch': typeof PitchRoute
  '/tools/wallet': typeof ToolsWalletRoute
  '/': typeof AppIndexRoute
  '/games/candle-hop': typeof AppGamesCandleHopRoute
  '/games/line-rider': typeof AppGamesLineRiderRoute
  '/games/lucky': typeof AppGamesLuckyRoute
  '/games/moonshot': typeof AppGamesMoonshotRoute
  '/games/range': typeof AppGamesRangeRoute
  '/menu/achievements': typeof AppMenuAchievementsRoute
  '/menu/customize': typeof AppMenuCustomizeRoute
  '/menu/deposit': typeof AppMenuDepositRoute
  '/menu/history': typeof AppMenuHistoryRoute
  '/menu/leaderboard': typeof AppMenuLeaderboardRoute
  '/menu/settings': typeof AppMenuSettingsRoute
  '/menu/stats': typeof AppMenuStatsRoute
  '/menu/username': typeof AppMenuUsernameRoute
  '/menu/withdraw': typeof AppMenuWithdrawRoute
  '/games': typeof AppGamesIndexRoute
  '/menu': typeof AppMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/console': typeof ConsoleRoute
  '/console-transparent': typeof ConsoleTransparentRoute
  '/design-system': typeof DesignSystemRoute
  '/export': typeof ExportRoute
  '/pitch': typeof PitchRoute
  '/tools/wallet': typeof ToolsWalletRoute
  '/_app/': typeof AppIndexRoute
  '/_app/games/candle-hop': typeof AppGamesCandleHopRoute
  '/_app/games/line-rider': typeof AppGamesLineRiderRoute
  '/_app/games/lucky': typeof AppGamesLuckyRoute
  '/_app/games/moonshot': typeof AppGamesMoonshotRoute
  '/_app/games/range': typeof AppGamesRangeRoute
  '/_app/menu/achievements': typeof AppMenuAchievementsRoute
  '/_app/menu/customize': typeof AppMenuCustomizeRoute
  '/_app/menu/deposit': typeof AppMenuDepositRoute
  '/_app/menu/history': typeof AppMenuHistoryRoute
  '/_app/menu/leaderboard': typeof AppMenuLeaderboardRoute
  '/_app/menu/settings': typeof AppMenuSettingsRoute
  '/_app/menu/stats': typeof AppMenuStatsRoute
  '/_app/menu/username': typeof AppMenuUsernameRoute
  '/_app/menu/withdraw': typeof AppMenuWithdrawRoute
  '/_app/games/': typeof AppGamesIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/console-transparent'
    | '/design-system'
    | '/export'
    | '/pitch'
    | '/tools/wallet'
    | '/games/candle-hop'
    | '/games/line-rider'
    | '/games/lucky'
    | '/games/moonshot'
    | '/games/range'
    | '/menu/achievements'
    | '/menu/customize'
    | '/menu/deposit'
    | '/menu/history'
    | '/menu/leaderboard'
    | '/menu/settings'
    | '/menu/stats'
    | '/menu/username'
    | '/menu/withdraw'
    | '/games/'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/console'
    | '/console-transparent'
    | '/design-system'
    | '/export'
    | '/pitch'
    | '/tools/wallet'
    | '/'
    | '/games/candle-hop'
    | '/games/line-rider'
    | '/games/lucky'
    | '/games/moonshot'
    | '/games/range'
    | '/menu/achievements'
    | '/menu/customize'
    | '/menu/deposit'
    | '/menu/history'
    | '/menu/leaderboard'
    | '/menu/settings'
    | '/menu/stats'
    | '/menu/username'
    | '/menu/withdraw'
    | '/games'
    | '/menu'
  id:
    | '__root__'
    | '/_app'
    | '/console'
    | '/console-transparent'
    | '/design-system'
    | '/export'
    | '/pitch'
    | '/tools/wallet'
    | '/_app/'
    | '/_app/games/candle-hop'
    | '/_app/games/line-rider'
    | '/_app/games/lucky'
    | '/_app/games/moonshot'
    | '/_app/games/range'
    | '/_app/menu/achievements'
    | '/_app/menu/customize'
    | '/_app/menu/deposit'
    | '/_app/menu/history'
    | '/_app/menu/leaderboard'
    | '/_app/menu/settings'
    | '/_app/menu/stats'
    | '/_app/menu/username'
    | '/_app/menu/withdraw'
    | '/_app/games/'
    | '/_app/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  ConsoleTransparentRoute: typeof ConsoleTransparentRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ExportRoute: typeof ExportRoute
  PitchRoute: typeof PitchRoute
  ToolsWalletRoute: typeof ToolsWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console-transparent': {
      id: '/console-transparent'
      path: '/console-transparent'
      fullPath: '/console-transparent'
      preLoaderRoute: typeof ConsoleTransparentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tools/wallet': {
      id: '/tools/wallet'
      path: '/tools/wallet'
      fullPath: '/tools/wallet'
      preLoaderRoute: typeof ToolsWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/withdraw': {
      id: '/_app/menu/withdraw'
      path: '/menu/withdraw'
      fullPath: '/menu/withdraw'
      preLoaderRoute: typeof AppMenuWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/username': {
      id: '/_app/menu/username'
      path: '/menu/username'
      fullPath: '/menu/username'
      preLoaderRoute: typeof AppMenuUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/stats': {
      id: '/_app/menu/stats'
      path: '/menu/stats'
      fullPath: '/menu/stats'
      preLoaderRoute: typeof AppMenuStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/settings': {
      id: '/_app/menu/settings'
      path: '/menu/settings'
      fullPath: '/menu/settings'
      preLoaderRoute: typeof AppMenuSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/leaderboard': {
      id: '/_app/menu/leaderboard'
      path: '/menu/leaderboard'
      fullPath: '/menu/leaderboard'
      preLoaderRoute: typeof AppMenuLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/history': {
      id: '/_app/menu/history'
      path: '/menu/history'
      fullPath: '/menu/history'
      preLoaderRoute: typeof AppMenuHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/deposit': {
      id: '/_app/menu/deposit'
      path: '/menu/deposit'
      fullPath: '/menu/deposit'
      preLoaderRoute: typeof AppMenuDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/customize': {
      id: '/_app/menu/customize'
      path: '/menu/customize'
      fullPath: '/menu/customize'
      preLoaderRoute: typeof AppMenuCustomizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/achievements': {
      id: '/_app/menu/achievements'
      path: '/menu/achievements'
      fullPath: '/menu/achievements'
      preLoaderRoute: typeof AppMenuAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/range': {
      id: '/_app/games/range'
      path: '/games/range'
      fullPath: '/games/range'
      preLoaderRoute: typeof AppGamesRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/moonshot': {
      id: '/_app/games/moonshot'
      path: '/games/moonshot'
      fullPath: '/games/moonshot'
      preLoaderRoute: typeof AppGamesMoonshotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/lucky': {
      id: '/_app/games/lucky'
      path: '/games/lucky'
      fullPath: '/games/lucky'
      preLoaderRoute: typeof AppGamesLuckyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/line-rider': {
      id: '/_app/games/line-rider'
      path: '/games/line-rider'
      fullPath: '/games/line-rider'
      preLoaderRoute: typeof AppGamesLineRiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/candle-hop': {
      id: '/_app/games/candle-hop'
      path: '/games/candle-hop'
      fullPath: '/games/candle-hop'
      preLoaderRoute: typeof AppGamesCandleHopRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppGamesCandleHopRoute: typeof AppGamesCandleHopRoute
  AppGamesLineRiderRoute: typeof AppGamesLineRiderRoute
  AppGamesLuckyRoute: typeof AppGamesLuckyRoute
  AppGamesMoonshotRoute: typeof AppGamesMoonshotRoute
  AppGamesRangeRoute: typeof AppGamesRangeRoute
  AppMenuAchievementsRoute: typeof AppMenuAchievementsRoute
  AppMenuCustomizeRoute: typeof AppMenuCustomizeRoute
  AppMenuDepositRoute: typeof AppMenuDepositRoute
  AppMenuHistoryRoute: typeof AppMenuHistoryRoute
  AppMenuLeaderboardRoute: typeof AppMenuLeaderboardRoute
  AppMenuSettingsRoute: typeof AppMenuSettingsRoute
  AppMenuStatsRoute: typeof AppMenuStatsRoute
  AppMenuUsernameRoute: typeof AppMenuUsernameRoute
  AppMenuWithdrawRoute: typeof AppMenuWithdrawRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppGamesCandleHopRoute: AppGamesCandleHopRoute,
  AppGamesLineRiderRoute: AppGamesLineRiderRoute,
  AppGamesLuckyRoute: AppGamesLuckyRoute,
  AppGamesMoonshotRoute: AppGamesMoonshotRoute,
  AppGamesRangeRoute: AppGamesRangeRoute,
  AppMenuAchievementsRoute: AppMenuAchievementsRoute,
  AppMenuCustomizeRoute: AppMenuCustomizeRoute,
  AppMenuDepositRoute: AppMenuDepositRoute,
  AppMenuHistoryRoute: AppMenuHistoryRoute,
  AppMenuLeaderboardRoute: AppMenuLeaderboardRoute,
  AppMenuSettingsRoute: AppMenuSettingsRoute,
  AppMenuStatsRoute: AppMenuStatsRoute,
  AppMenuUsernameRoute: AppMenuUsernameRoute,
  AppMenuWithdrawRoute: AppMenuWithdrawRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  ConsoleTransparentRoute: ConsoleTransparentRoute,
  DesignSystemRoute: DesignSystemRoute,
  ExportRoute: ExportRoute,
  PitchRoute: PitchRoute,
  ToolsWalletRoute: ToolsWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
